# Generated by Django 3.1.7 on 2021-02-27 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remoute_addr', models.GenericIPAddressField(verbose_name='IP-адрес пользователя')),
                ('crsf_token', models.CharField(max_length=50, verbose_name='CRSF TOKEN')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('origin', models.ImageField(upload_to='', verbose_name='Оригинал изображения')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imageApp.customer', verbose_name='Владелец изображения')),
            ],
        ),
    ]
