# Generated by Django 3.1.7 on 2021-02-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageApp', '0002_auto_20210227_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='crsf_token',
            field=models.CharField(max_length=50, verbose_name='CRSF TOKEN'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='remoute_addr',
            field=models.GenericIPAddressField(verbose_name='IP-адрес пользователя'),
        ),
    ]
