# Generated by Django 3.1.7 on 2021-02-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageApp', '0003_auto_20210227_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='crsf_token',
        ),
        migrations.AddField(
            model_name='customer',
            name='csrf_token',
            field=models.CharField(default=1, max_length=50, verbose_name='CSRF-TOKEN'),
            preserve_default=False,
        ),
    ]
