# Generated by Django 3.1.7 on 2021-02-27 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageApp', '0004_auto_20210227_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='remoute_addr',
            new_name='remote_addr',
        ),
    ]
